### ISSUE TITLE
Is this project alive or dead?

### ISSUE THREAD

**Issue by MikePapinski** [LambdaSharp/WebSockets-Sample#12]

**Comment by bjorg** [comment]
It's not so much a project as a sample app showing how various pieces fit together.

**Comment by MikePapinski** [comment]
I am having problems when trying to 'lash deploy' it.
ERROR: CREATE_FAILED ResourceHandler [AWS::Lambda::Function]: Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [50]. (Service: Lambda, Status Code: 400, Request ID: 73df6dbe-b175-4822-a532-fcdd70231348, Extended Request ID: null)" (RequestToken: 80034c2e-dba9-97da-472e-b5a6c5f55f81, HandlerErrorCode: InvalidRequest) [LambdaSharp.Chat:1.0-DEV@lambdasharp-core-deploymentbucketresource-1quxkwsor6fwq]

The example with simple static page worked for me but I am having troubles to deploy the chat sample. I need a good example with blazor-cognito-restapi-lambda-dynamoDB integration for my SaaS app. Is there any forum/community around LambdaSharp? I really like the concept and would like to use it in production. I need to move from containers to Serverless on AWS.

I would really appreciate any help with making my setup work on lambdasharp.

**Comment by MikePapinski** [comment]
I increased my Lambda concurrency limit from 50 to 1000 as default and I was able to deploy it but when I go to the URL I have access denied.

 AccessDeniedAccess DeniedKBW5RH6WAT9VEAMGCaYHDgyB6QXbs7iaLmmwXobnfvawty/ro4cP2DTQhAyCjGppfBXmsEFvlGDr335qkh4Il2Qkuck=
 
 My deployed URL: 
 https://d2thk1kfiaj67s.cloudfront.net/

**Comment by bjorg** [comment]
That's normal on first deploy. It takes ~1 hour for the `OriginAccessIdentity` to propagate between CloudFront and S3. Until it does, CloudFront forwards incoming requests to the S3 bucket, which is locked down. It's annoying and not clear at first, but that is how it works. 🤷‍♂️

**Comment by bjorg** [comment]
On the `ReservedConcurrentExecutions` error, did you modify the function definition and added reserved concurrency? It's not there by default.

**Comment by bjorg** [comment]
I usually answer questions on the [AWS Developers](awsdevelopers.slack.com) slack channel under the `#dotnet` topic. Let me know if you need an invite for it. You can email me at lambdasharp@gmail.com.

**Comment by MikePapinski** [comment]
> I usually answer questions on the [AWS Developers](awsdevelopers.slack.com) slack channel under the `#dotnet` topic. Let me know if you need an invite for it. You can email me at [lambdasharp@gmail.com](mailto:lambdasharp@gmail.com).

thx, I have send you an email.

for the ReservedConcurrentExecutions I just went on aws portal and submit a ticket to increase the concurrency from 50 to 1000 which was highlighted as default on the portal. Today I had a call from aws support to confirm this ticket and after that the deploy worked.

I am very new to Serverless concepts and AWS. I used to run my service from docker compose hosted on digital ocean vm but CI/CD was nightmare so I decided to go Serverless on AWS.

I will play around with this chat, maybe I will make it work.

**Comment by bjorg** [comment]
Got your email. You should get an invite link soon.

**Comment by MikePapinski** [comment]
Looks like this sample is still not working. When I go to /Login I get the AccessDeniedAccess  still. Maybe OriginAccessIdentity did not get there yet?
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/48183086/146054472-98311c32-f2c1-48f8-9249-85b6e466bbbe.png">

**Comment by MikePapinski** [comment]
Ok when I wrote the post it started to work. I have finally good base to start. Closing this issue. Thank You!
